services:
  app:
    build: .
    ports:
      - '3000:3000'
    container_name: docker-node
    restart: always
    command: npm run dev
    depends_on:
      - mongo
      - mysql
    networks:
      - app-network

  mongo:
    image: mongo
    container_name: docker-mongo
    restart: always
    ports:
      - '27017:27017'
    networks:
      - app-network

  mysql:
    image: mysql
    container_name: docker-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: test
    ports:
      - '3306:3306'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
