services:
  app:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    container_name: docker-node
    restart: always
    command: npm run dev
    depends_on:
      - mongo
      - mysql
    networks:
      - app-network

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    env_file:
      - .env
    container_name: $MONGO_HOST
    restart: always
    networks:
      - app-network

  mysql:
    image: mysql
    ports:
      - '3306:3306'
    env_file:
      - .env
    container_name: $MYSQL_HOST
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: test
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
