services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - $APP_PORT:$APP_PORT
    container_name: $APP_CONTAINER_NAME
    restart: always
    command: npm run dev
    depends_on:
      - mongo
      - mysql
    networks:
      - app-network

  mongo:
    image: mongo
    env_file:
      - .env
    ports:
      - $MONGO_PORT:$MONGO_PORT
    container_name: $MONGO_CONTAINER_HOST
    restart: always
    networks:
      - app-network

  mysql:
    image: mysql
    env_file:
      - .env
    ports:
      - $MYSQL_PORT:$MYSQL_PORT
    container_name: $MYSQL_CONTAINER_HOST
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
